trigger:
  - "*"

pool:
  vmImage: 'ubuntu-latest'
container: munzli/azp-container:latest

steps:
  - task: Docker@2
    displayName: 'Build image'
    inputs:
      repository: $(AWS_ACCOUNT_ID).dkr.ecr.eu-west-1.amazonaws.com/operators/aws-service-operator
      command: build
      Dockerfile: Dockerfile
      # hardcoded version
      tags: v0.0.4

  - task: Bash@3
    displayName: 'AWS login'
    inputs:
      targetType: 'inline'
      script: |
        export AWS_SECRET_ACCESS_KEY=$(AWS_SECRET_ACCESS_KEY)
        temp_role=$(aws sts assume-role \
                            --role-arn "arn:aws:iam::$(AWS_ACCOUNT_ID):role/ECRPowerUser" \
                            --role-session-name "ecr")

        export AWS_ACCESS_KEY_ID=$(echo $temp_role | jq -r .Credentials.AccessKeyId)
        export AWS_SECRET_ACCESS_KEY=$(echo $temp_role | jq -r .Credentials.SecretAccessKey)
        export AWS_SESSION_TOKEN=$(echo $temp_role | jq -r .Credentials.SessionToken)

        aws ecr get-login --no-include-email --region eu-west-1 | sh -

  - task: Bash@3
    displayName: 'ECR push'
    inputs:
      targetType: 'inline'
      script: |
        docker push $(AWS_ACCOUNT_ID).dkr.ecr.eu-west-1.amazonaws.com/operators/aws-service-operator:v0.0.4
      condition: succeeded()