apiVersion: service-operator.aws/v1alpha1
kind: DynamoDB
metadata:
  name: example-table-name
spec:
  tableName: example_table_name
  hashAttribute:
    name: user_id
    type: S
  rangeAttribute:
    name: created_at
    type: S
  # set zero for on-demand billing
  readCapacityUnits: 0
  writeCapacityUnits: 0
  secondaryIndexName: custom_name
  secondaryHashAttribute:
    name: created_at
    type: S
  secondaryRangeAttribute:
    name: modified_at
    type: S