apiVersion: service-operator.aws/v1alpha1
kind: SQSQueue
metadata:
  name: example-sqs-queue-name
spec:
  queueName: example-sqs-queue-name # if not specified queue name will be concatenated
  contentBasedDeduplication: true
  delaySeconds: 5
  usedeadletterQueue: false
  maximumMessageSize: 262144
  messageRetentionPeriod: 345600
  visibilityTimeout: 30


