apiVersion: service-operator.aws/v1alpha1
kind: CloudFormationTemplate
metadata:
  name: dynamodb
data:
  key: dynamodb.yaml
  template: |
    AWSTemplateFormatVersion: 2010-09-09
    Description: 'AWS Service Operator - Amazon DynamoDB (aso-1otq2cgc4)'
    Parameters:
      Namespace:
        Description: >-
          This is the namespace for the Kubernetes object.
        Type: String
      ResourceVersion:
        Type: String
        Description: >-
          This is the resource version for the Kubernetes object.
      ResourceName:
        Description: >-
          This is the resource name for the Kubernetes object
        Type: String
      ClusterName:
        Description: >-
          This is the cluster name for the operator
        Type: String
      TableName:
        Description: >-
          Must contain only lowercase letters, numbers and hyphens.
        Type: String
      HashAttributeName:
        Type: String
        Description: Name of the Hash key
      HashAttributeType:
        Type: String
        AllowedValues:
          - S
          - N
          - B
        Default: "S"
        Description: AttributeType for Hash key
      RangeAttributeName:
        Type: String
        Description: Name of the Range key
      RangeAttributeType:
        Type: String
        AllowedValues:
          - S
          - N
          - B
          - ""
        Default: "S"
        Description: AttributeType for the Range key
      SecondaryIndexName:
        Description: >-
          Must contain only lowercase letters, numbers and hyphens.
        Type: String
      SecondaryHashAttributeName:
        Type: String
        Description: Name of the secondary hash key
      SecondaryHashAttributeType:
        Type: String
        AllowedValues:
          - S
          - N
          - B
          - ""
        Default: "S"
        Description: AttributeType for the secondary index key
      SecondaryRangeAttributeName:
        Type: String
        Description: Name of the secondary range key
      SecondaryRangeAttributeType:
        Type: String
        AllowedValues:
          - S
          - N
          - B
          - ""
        Default: "S"
        Description: AttributeType for the secondary range key
      ReadCapacityUnits:
        Type: String
        Description: Read ReadCapacity Units
        Default: "5"
      WriteCapacityUnits:
        Type: String
        Description: Write Capacity Units
        Default: "5"
    Conditions:
      HasRangeAttribute:
        !Not [!Equals [!Ref RangeAttributeName, ""]]
      HasSecondaryHashAttribute:
        !Not [!Equals [!Ref SecondaryHashAttributeName, ""]]
      HasSecondaryRangeAttribute:
        !Not [!Equals [!Ref SecondaryRangeAttributeName, ""]]
      HasSecondaryIndexName:
        !Not [!Equals [!Ref SecondaryIndexName, ""]]
      CreateSecondaryHashAttribute: !And
        - !Not [!Equals [!Ref SecondaryHashAttributeName, !Ref HashAttributeName]]
        - !Not [!Equals [!Ref SecondaryHashAttributeName, !Ref RangeAttributeName]]
        - !Condition HasSecondaryHashAttribute
      CreateSecondaryRangeAttribute: !And
        - !Not [!Equals [!Ref SecondaryRangeAttributeName, !Ref HashAttributeName]]
        - !Not [!Equals [!Ref SecondaryRangeAttributeName, !Ref RangeAttributeName]]
        - !Condition HasSecondaryRangeAttribute
    Resources:
      DynamoDBTable:
        Type: "AWS::DynamoDB::Table"
        Properties:
          TableName: !Ref TableName
          KeySchema:
            -
              AttributeName: !Ref HashAttributeName
              KeyType: "HASH"
            - !If
              - HasRangeAttribute
              -
                AttributeName: !Ref RangeAttributeName
                KeyType: "RANGE"
              - !Ref "AWS::NoValue"
          AttributeDefinitions:
            -
              AttributeName: !Ref HashAttributeName
              AttributeType: !Ref HashAttributeType
            - !If
              - HasRangeAttribute
              -
                AttributeName: !Ref RangeAttributeName
                AttributeType: !Ref RangeAttributeType
              - !Ref "AWS::NoValue"
            - !If
              - CreateSecondaryHashAttribute
              -
                AttributeName: !Ref SecondaryHashAttributeName
                AttributeType: !Ref SecondaryHashAttributeType
              - !Ref "AWS::NoValue"
            - !If
              - CreateSecondaryRangeAttribute
              -
                AttributeName: !Ref SecondaryRangeAttributeName
                AttributeType: !Ref SecondaryRangeAttributeType
              - !Ref "AWS::NoValue"
          ProvisionedThroughput:
            ReadCapacityUnits: !Ref ReadCapacityUnits
            WriteCapacityUnits: !Ref WriteCapacityUnits
          GlobalSecondaryIndexes: !If
            - HasSecondaryHashAttribute
            -
              - IndexName: !If
                - HasSecondaryIndexName
                - !Ref SecondaryIndexName
                - !Join
                 - '-'
                 - - !Ref SecondaryHashAttributeName
                   - 'index'
                KeySchema:
                  -
                    AttributeName: !Ref SecondaryHashAttributeName
                    KeyType: "HASH"
                  - !If
                    - HasSecondaryRangeAttribute
                    -
                      AttributeName: !Ref SecondaryRangeAttributeName
                      KeyType: "RANGE"
                    - !Ref "AWS::NoValue"
                Projection: 
                  ProjectionType: "ALL"
                ProvisionedThroughput:
                  ReadCapacityUnits: !Ref ReadCapacityUnits
                  WriteCapacityUnits: !Ref WriteCapacityUnits
            - !Ref "AWS::NoValue"
          Tags:
            - Key: Namespace
              Value: !Ref Namespace
            - Key: ResourceVersion
              Value: !Ref ResourceVersion
            - Key: ResourceName
              Value: !Ref ResourceName
            - Key: ClusterName
              Value: !Ref ClusterName
            - Key: Heritage
              Value: operator.aws
    Outputs:
      TableName:
        Description: Name of the DynamoDB Table
        Value: !Ref DynamoDBTable
      TableArn:
        Description: Arn of the DynamoDB Table
        Value: !GetAtt DynamoDBTable.Arn
