# Default values for localstack.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
localstack:
  #  default of hostExternal {{service.name}}.{{namespace deployed into}}
  #  hostExternal:
  port: 8080
  useSsl: "true"
  defaultRegion: "localstack"
  kinesisErrorProbability: "0.0"
  dynamodbErrorProbability: "0.0"
  lambdaExecutor: "local"
  services:
    apigateway:
      name: apigateway
      enabled: false
      endpoint: ""
      internalPort: 4567
      externalPort: 4567
      # nodePort:  31567
    cloudformation:
      name: cloudformation
      enabled: false
      endpoint: ""
      internalPort: 4581
      externalPort: 458
      # nodePort: 31581
    dynamodb:
      name: dynamodb
      enabled: false
      endpoint: ""
      internalPort: 4569
      externalPort: 4569
      # nodePort:  31569
    elasticsearch:
      name: elasticsearch
      enabled: false
      endpoint: ""
      internalPort: 4571
      externalPort: 4571
      # nodePort: 31571
    kinesis:
      name: kinesis
      enabled: false
      endpoint: ""
      internalPort: 4568
      externalPort: 4568
      # nodePort: 31568
    s3:
      name: s3
      enabled: false
      endpoint: ""
      internalPort: 4572
      externalPort: 4572
      # nodePort: 31572
    sns:
      name: sns
      enabled: false
      endpoint: ""
      internalPort: 4575
      externalPort: 4575
      # nodePort: 31575
    sqs:
      name: sqs
      enabled: false
      endpoint: ""
      internalPort: 4576
      externalPort: 4576
      # nodePort: 31576
    ssm:
      name: ssm
      enabled: false
      internalPort: 4583
      externalPort: 4583
      # nodePort: 31583
    dynamodbstreams:
      name: dynamodbstreams
      enabled: false
      internalPort: 4570
      externalPort: 4570
      # nodePort:  31570
    firehose:
      name: firehose
      enabled: false
      internalPort: 4573
      externalPort: 4573
      # nodePort: 31573
    lambda:
      name: lambda
      enabled: false
      internalPort: 4574
      externalPort: 4574
      # nodePort:  31574
    redshift:
      name: redshift
      enabled: false
      internalPort: 4577
      externalPort: 4577
      # nodePort: 31577
    es:
      name: es
      enabled: false
      internalPort: 4578
      externalPort: 4578
      # nodePort: 31578
    ses:
      name: ses
      enabled: false
      internalPort: 4579
      externalPort: 4579
      # nodePort: 31579
    route53:
      name: route53
      enabled: false
      internalPort: 4580
      externalPort: 4580
      # nodePort:  31580
    cloudwatch:
      name: cloudwatch
      enabled: false
      internalPort: 4582
      externalPort: 4582
      # nodePort: 31582
    secretsmanager:
      name: secretsmanager
      enabled: false
      internalPort: 4584
      externalPort: 4584
      # nodePort: 31584
    iam:
      name: iam
      enabled: false
      internalPort: 4593
      externalPort: 4593
      # nodePort: 31593
    kms:
      name: kms
      enabled: false
      internalPort: 4599
      externalPort: 4599
      # nodePort: 31599
    sts:
      name: sts
      enabled: false
      internalPort: 4592
      externalPort: 4592
      # nodePort: 31592

replicaCount: 1

image:
  repository: localstack/localstack
  tag: latest
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  paths: ["/"]
  hosts: []
  #  - chart-example.local
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #  cpu: 100m
  #  memory: 128Mi
  # requests:
  #  cpu: 100m
  #  memory: 128Mi

## Persist data to a persitent volume
persistence:
  enabled: false
  ## Name of existing persistent volume to attach
  # existingClaim: ""

  ##  Persistent Volume Storage Class
  ## If defined, storageClassName: <storageClass>
  ## If set to "-", storageClassName: "", which disables dynamic provisioning
  ## If undefined (the default) or set to null, no storageClassName spec is
  ##   set, choosing the default provisioner.  (gp2 on AWS, standard on
  ##   GKE, AWS & OpenStack)
  ##
  # storageClass: "-"

  ## Persistent Volume Access Mode.
  accessMode: ReadWriteOnce

  ## Persistent Volume Storage Size.
  size: 8Gi

nodeSelector: {}

tolerations: []

affinity: {}

